// apps/angular/src/app/pages/resource-page/resource-page.ts
/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

import {
  Component,
  DestroyRef,
  HostListener,
  computed,
  effect,
  inject,
  OnInit,
  signal,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, Router } from '@angular/router';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzTagModule } from 'ng-zorro-antd/tag';
import type { ActionDef, ColumnDef, ResourceConfig, Row } from '../../config/types';
import { accentOf } from '../../config/types';
import { http, qs, type PageData } from '../../core/api.service';
import { text } from '../../core/format';
import { tr } from '../../core/i18n.service';
import { Toast } from '../../core/toast.service';
import { TrPipe } from '../../core/tr.pipe';
import { IconComponent } from '../../ui/icon';
import {
  TONE_COLOR,
  cellOf,
  flattenTree,
  inferColumns,
  inferDetailItems,
  specTags,
  take,
  type Cell,
} from './columns';
import { ResourceForm } from './resource-form';

const DEFAULT_LIMIT = 15;
// ponytail: 后端部分 service 把 limit 夹在 [1,100]，超限静默截断，这里先对齐上限
const MAX_LIMIT = 100;
const PAGE_SIZES = [15, 30, 50, 100];

interface RowView {
  row: Row;
  cells: Cell[];
}

interface Pending {
  kind: 'delete' | 'action';
  row: Row;
  act?: ActionDef;
}

function actionCount(cfg: ResourceConfig | null): number {
  // 详情 + 删除是固定两颗，有 fields 才有编辑
  let n = 2;
  if (cfg?.fields) n += 1;
  return n + (cfg?.actions?.length ?? 0);
}

function rowLabel(row: Row): string {
  return String(row['code'] ?? row['name'] ?? row['title'] ?? row['username'] ?? row['id'] ?? '');
}

function msg(e: unknown): string {
  return e instanceof Error ? e.message : '操作失败';
}

/**
 * 配置驱动的资源页引擎 —— 一份组件驱动全部资源列表页。
 *
 * 与 React `components/ResourcePage.tsx` 逐项对应；差别只在框架层：
 * 状态用 signal（effect 承担 useEffect 的依赖重跑）、模板只做展示、
 * 所有取值/格式化在 columns.ts + 本类里完成（模板不被 tsc 检查，逻辑放模板外）。
 */
@Component({
  selector: 'app-resource-page',
  standalone: true,
  imports: [NzButtonModule, NzTagModule, TrPipe, IconComponent, ResourceForm],
  templateUrl: './resource-page.html',
  styleUrl: './resource-page.less',
})
export class ResourcePage implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly toast = inject(Toast);
  private readonly destroyRef = inject(DestroyRef);

  /** 路由 data 里的配置与菜单标签（不依赖 withComponentInputBinding） */
  readonly cfg = signal<ResourceConfig | null>(null);
  readonly label = signal('');
  readonly accent = signal<string | undefined>(undefined);

  // ── 查询条件 ──
  readonly page = signal(1);
  readonly limit = signal(DEFAULT_LIMIT);
  readonly keyword = signal('');
  readonly filter = signal<string | number | null>(null);
  private readonly tick = signal(0);

  // ── 列表状态 ──
  readonly rows = signal<Row[]>([]);
  readonly total = signal(0);
  readonly loading = signal(true);
  readonly error = signal('');
  /** 模板用：分页器显隐（服务端分页恒显示；本地分页只有多于一页才显示） */
  readonly paged = signal(true);

  // ── 弹窗状态 ──
  readonly editing = signal<Row | 'new' | null>(null);
  readonly detail = signal<Row | null>(null);
  /** 详情接口回包（cfg.detailFetch 时才拉）：列表行没有关系数据，规格属性只在这份里 */
  readonly detailFull = signal<Row | null>(null);
  readonly pending = signal<Pending | null>(null);
  readonly pw = signal('');
  readonly busy = signal(false);

  readonly pageSizes = PAGE_SIZES;
  readonly skeleton = [0, 1, 2, 3];

  /** 请求序号：丢弃过期响应（对齐 React 的 alive 标记） */
  private reqSeq = 0;
  /**
   * 详情请求序号：**必须与列表的 reqSeq 分开** —— 共用一个序号时，
   * 打开详情会把在飞的列表 reload 判成过期，它的 finally 不再复位 loading，
   * 骨架屏就永久卡住了。
   */
  private detailSeq = 0;
  /**
   * 后端整表下发（裸数组 / 无 total 的 list，含权限树）时的全量行缓存：
   * 切页只在本地切片，不再重拉；筛选条件变了（指纹不符）才重新请求。
   * 非 signal 字段：effect 里读信号又写同一信号会多跑一轮。
   */
  private local: Row[] | null = null;
  private localKey = '';

  /** 显式配置优先，否则从首批行数据推断 */
  readonly cols = computed<ColumnDef[]>(() => {
    const cfg = this.cfg();
    if (!cfg) return [];
    return cfg.columns ?? inferColumns(this.rows(), cfg.endpoint);
  });

  /** 行视图：单元格已格式化，模板不参与任何取值逻辑 */
  readonly view = computed<RowView[]>(() => {
    const cols = this.cols();
    return this.rows().map((row) => ({ row, cells: cols.map((c) => cellOf(c, row)) }));
  });

  readonly pages = computed(() =>
    Math.max(1, Math.ceil(this.total() / (this.limit() || DEFAULT_LIMIT))),
  );
  readonly actionWidth = computed(() => Math.max(86, 32 * actionCount(this.cfg())));
  readonly detailItems = computed(() => {
    const d = this.detail();
    // 传 cols：列配了 kind:'tags' 的字段（如 spec.attrs）在详情行渲染胶囊而非 JSON 原文
    return d ? inferDetailItems(d, this.cols()) : [];
  });
  /**
   * 规格属性胶囊：按 SKU 的 `spec_id` 取所属规格的 `attrs`（JSON 字符串），摊平成「键:值」一排。
   *
   * SKU 表自 2026-09-12 起不再自带 `spec_attrs` 副本（属性只存在 erp_product_spec），
   * 故数据源改为 `skus[].spec.attrs`（后端 findProductWithRelations 已 with('skus.spec')）。
   * 这里渲染的是**该规格声明的属性全集**，不是某个 SKU 的选中值——选中值当前无处存储。
   * 多个 SKU 可能引用同一规格，故按文本去重（否则同一规格会被重复列一遍）。
   * 解析全部在 columns.specTags 里；模板不过 tr（键是用户数据，不是词典词条）。
   */
  readonly detailSpecs = computed(() => {
    const skus = this.detailFull()?.['skus'];
    if (!Array.isArray(skus)) return [];
    const tags = skus.flatMap((s) => {
      if (!s || typeof s !== 'object') return [];
      const spec = (s as Row)['spec'];
      return spec && typeof spec === 'object' ? specTags((spec as Row)['attrs']) : [];
    });
    return [...new Set(tags)];
  });
  /** 页面标题：路由带的 label 只做兜底（配置必有 title） */
  readonly title = computed(() => this.cfg()?.title || this.label());

  /** 确认框文案（React 在 JSX 里内联，这里挪到 computed 保持模板简单） */
  readonly pendingTitle = computed(() => {
    const p = this.pending();
    if (!p) return '';
    if (p.kind === 'delete') return tr('确认删除');
    return p.act?.label ? tr(p.act.label) : tr('确认操作');
  });
  readonly pendingMsg = computed(() => {
    const p = this.pending();
    if (!p) return '';
    return p.kind === 'delete'
      ? tr('确定删除「{name}」？该操作不可恢复。', { name: text(rowLabel(p.row)) })
      : tr('确定执行「{act}」吗？', { act: p.act?.label ?? '' });
  });
  readonly needPassword = computed(() => {
    const p = this.pending();
    if (!p) return false;
    return p.kind === 'delete'
      ? this.cfg()?.deleteNeedsPassword === true
      : p.act?.requirePassword === true;
  });

  constructor() {
    // 查询条件任一变即重新拉取 —— 对齐 React useEffect 的依赖数组 [page,limit,keyword,filter,tick]
    effect(() => {
      void this.reload();
    });
  }

  ngOnInit(): void {
    // 用订阅而非 snapshot：同一组件实例被路由复用时 snapshot 不会更新
    this.route.data.pipe(takeUntilDestroyed(this.destroyRef)).subscribe((d) => {
      const cfg = d['cfg'] as ResourceConfig | undefined;
      if (!cfg) return;
      this.cfg.set(cfg);
      this.label.set((d['label'] as string | undefined) ?? '');
      this.accent.set(accentOf((d['moduleKey'] as string | undefined) ?? cfg.moduleKey));
      // 切页/切资源时回到初始查询态（React 靠组件重挂载，Angular 靠这里显式复位）
      this.page.set(1);
      this.limit.set(DEFAULT_LIMIT);
      this.keyword.set('');
      this.filter.set(null);
      this.local = null;
      this.localKey = '';
      this.paged.set(true);
    });
  }

  /** 查询指纹：端点/固定参数/关键词/筛选；不含 page/limit —— 本地切页不该重拉 */
  private fetchKey(cfg: ResourceConfig): string {
    return [
      cfg.endpoint,
      JSON.stringify(cfg.params ?? {}),
      this.keyword(),
      this.filter() ?? '',
    ].join('|');
  }

  private async reload(): Promise<void> {
    const cfg = this.cfg();
    if (!cfg) return;
    const key = this.fetchKey(cfg);
    // 本地分页且条件没变：数据已在手，切页只重新切片
    if (this.local && this.localKey === key) {
      this.sliceLocal();
      return;
    }
    this.loading.set(true);
    this.error.set('');
    const params: Record<string, string | number | undefined | null> = {
      ...(cfg.params ?? {}),
      keyword: this.keyword() || undefined,
    };
    if (cfg.filters && this.filter() !== null) params[cfg.filters.key] = this.filter();
    params['page'] = this.page();
    params['limit'] = Math.min(this.limit(), MAX_LIMIT);
    const seq = ++this.reqSeq;
    try {
      const data = await http.get<Row[] | PageData<Row>>(`${cfg.endpoint}${qs(params)}`);
      if (seq !== this.reqSeq) return;
      // 后端三种列表形状，判据只能是「回显了 page」：真分页的接口一定会回显它。
      // `{list,total}` 无 page 的那批（多组织/账套期间/合并报表…）照样整表下发，
      // 按 total 判会给它们画一个翻不动的分页器（渲染几页、行永远是同一批）。
      if (!Array.isArray(data) && data.page !== undefined) {
        this.local = null;
        this.localKey = '';
        this.rows.set(data.list ?? []);
        this.total.set(Number(data.total ?? 0));
        this.paged.set(true);
      } else {
        // 裸数组、`{list}`、`{list,total}` 无 page：整表收下本地切片（权限树就是这种）
        this.setLocal(Array.isArray(data) ? data : (data.list ?? []), key);
      }
    } catch (e) {
      if (seq === this.reqSeq) this.error.set(e instanceof Error ? e.message : '加载失败');
    } finally {
      if (seq === this.reqSeq) this.loading.set(false);
    }
  }

  /** 整表响应转本地分页源：树形行先拍平成带 __depth 的平铺行（子节点才可见） */
  private setLocal(rows: Row[], key: string): void {
    this.local = rows.some((r) => Array.isArray(r['children'])) ? flattenTree(rows) : rows;
    this.localKey = key;
    this.sliceLocal();
  }

  /** 本地切片：rows 只放当前页，total 记全量（分页器按它算页数） */
  private sliceLocal(): void {
    const all = this.local ?? [];
    const size = Math.min(this.limit(), MAX_LIMIT) || DEFAULT_LIMIT;
    const pages = Math.max(1, Math.ceil(all.length / size));
    // 删/刷新后行数变少可能落在空页：夹回最后一页，别跳回第 1 页
    if (this.page() > pages) this.page.set(pages);
    const start = (this.page() - 1) * size;
    this.rows.set(all.slice(start, start + size));
    this.total.set(all.length);
    this.paged.set(all.length > size);
  }

  refresh(): void {
    // 刷新语义是「重新问后端」，本地缓存必须作废，否则本地分页会拿旧数据切片
    this.local = null;
    this.localKey = '';
    this.tick.update((t) => t + 1);
  }

  // ── 查询交互 ──
  onKeyword(e: Event): void {
    this.keyword.set((e.target as HTMLInputElement).value);
    this.page.set(1);
  }

  onLimit(e: Event): void {
    this.limit.set(Number((e.target as HTMLInputElement).value));
    this.page.set(1);
  }

  onFilter(v: string | number | null): void {
    this.filter.set(v);
    this.page.set(1);
  }

  /** 二次确认密码输入（原生 input，不走 ngModel） */
  onPw(e: Event): void {
    this.pw.set((e.target as HTMLInputElement).value);
  }

  go(p: number): void {
    this.page.set(p);
  }

  // ── 弹窗开关 ──
  openNew(): void {
    this.editing.set('new');
  }

  openEdit(row: Row): void {
    this.editing.set(row);
  }

  closeForm(): void {
    this.editing.set(null);
  }

  onSaved(): void {
    this.editing.set(null);
    this.refresh();
  }

  openDetail(row: Row): void {
    this.detail.set(row);
    this.detailFull.set(null);
    if (this.cfg()?.detailFetch) void this.loadDetail(row);
  }

  closeDetail(): void {
    // 序号自增：关掉后回来的响应直接作废，不再写信号
    this.detailSeq++;
    this.detail.set(null);
    this.detailFull.set(null);
  }

  /**
   * 详情接口回包：列表行缺关系数据（如 skus）时按需补拉。
   * 失败静默 —— 弹层照旧显示列表行字段，只是没有规格属性，不打断查看。
   */
  private async loadDetail(row: Row): Promise<void> {
    const cfg = this.cfg();
    const id = String(take(row, 'id') ?? '');
    if (!cfg || !id) return;
    const seq = ++this.detailSeq;
    try {
      const full = await http.get<Row>(`${cfg.endpoint}/${id}`);
      if (seq !== this.detailSeq) return;
      this.detailFull.set(full);
    } catch {
      // 详见方法注释：静默降级
    }
  }

  askDelete(row: Row): void {
    this.pw.set('');
    this.pending.set({ kind: 'delete', row });
  }

  askAction(row: Row, act: ActionDef): void {
    this.pw.set('');
    this.pending.set({ kind: 'action', row, act });
  }

  closePending(): void {
    if (!this.busy()) this.pending.set(null);
  }

  /**
   * Esc 关闭最上层弹窗 —— 对齐 React Modal 的 window keydown 监听。
   * React 每个弹窗各挂一个监听，同一时刻至多开一个，这里合并成一个就够。
   */
  @HostListener('document:keydown.escape')
  onEsc(): void {
    if (this.pending()) this.closePending();
    else if (this.detail()) this.closeDetail();
    else if (this.editing()) this.closeForm();
  }

  confirm(): void {
    const p = this.pending();
    if (!p) return;
    if (p.kind === 'delete') void this.doDelete(p.row, this.pw());
    else if (p.act) void this.runAction(p.act, p.row, this.pw());
  }

  /** 动作按钮是否显示：path 返回 null 表示当前行不可用 */
  showAction(act: ActionDef, row: Row): boolean {
    return !act.path || act.path(row) !== null;
  }

  /** 动作按钮是否为文字按钮（只有 sm/outline/danger 显示 label，对齐 React iconOnly 判定） */
  showLabel(act: ActionDef): boolean {
    return !!act.variant && !act.variant.startsWith('icon');
  }

  private async doDelete(row: Row, password: string): Promise<void> {
    const cfg = this.cfg();
    if (!cfg) return;
    const id = String(take(row, 'id') ?? '');
    this.busy.set(true);
    try {
      // 敏感资源（用户/角色/权限）删除需二次密码，后端 confirmPassword 校验
      await http.del(`${cfg.endpoint}/${id}`, cfg.deleteNeedsPassword ? { password } : undefined);
      this.toast.success(tr('删除成功'));
      this.pending.set(null);
      this.refresh();
    } catch (e) {
      this.toast.error(msg(e));
    } finally {
      this.busy.set(false);
    }
  }

  private async runAction(act: ActionDef, row: Row, password: string): Promise<void> {
    const path = act.path?.(row);
    if (!path) return;
    this.busy.set(true);
    try {
      const body = act.body?.(row, password) ?? {};
      if (act.method === 'GET') await http.get(path);
      else if (act.method === 'PUT') await http.put(path, body);
      else await http.post(path, body);
      this.toast.success(act.message ? tr(act.message) : tr('操作成功'));
      this.pending.set(null);
      this.refresh();
      if (act.navTo) void this.router.navigateByUrl(act.navTo(row));
    } catch (e) {
      this.toast.error(msg(e));
    } finally {
      this.busy.set(false);
    }
  }

  /** 徽标 tone → nz-tag 颜色（模板里用，避免内联字面量映射） */
  tone(t: Cell['tone']): string {
    return t ? TONE_COLOR[t] : 'default';
  }
}

// apps/react/src/components/ResourcePage.tsx
/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { DataTable, take } from '@/components/DataTable';
import {
  Btn,
  Chips,
  ConfirmDialog,
  DescList,
  Field,
  Input,
  Modal,
  PageHead,
  Select,
  Textarea,
} from '@/components/ui';
import { api, http, qs, type PageData } from '@/lib/api';
import { useToast } from '@/lib/toast';
import { text } from '@/lib/format';
import { useTr } from '@/lib/i18n';
import { accentOf, type ActionDef, type FieldOption, type FieldSource, type FormField, type Row } from '@/config/types';
import { inferColumns, inferDetailItems } from '@/lib/defaults';
import { loadOptions, prefetch } from '@/lib/options';

/**
 * 配置驱动的通用 CRUD 页。
 *
 * 一个业务资源 = 一份 ResourceConfig（列 + 筛选 + 表单字段 + 行内动作），
 * 列表/搜索/分页/新增/编辑/删除/详情/业务动作全部复用本组件。
 * 后端新增资源时前端只加配置，不写页面。
 *
 * 兼容两种列表形状：分页对象 {list,total,page,limit} 与全量数组；
 * 收到数组时自动隐藏分页器，无需在配置里声明。
 */

const DEFAULT_LIMIT = 15;
// ponytail: 后端部分 service 把 limit 夹在 [1,100]，超限静默截断，这里先对齐上限
const MAX_LIMIT = 100;

export function ResourcePage({
  cfg,
  initialQuery,
}: {
  cfg: import('@/config/types').ResourceConfig;
  initialQuery?: string;
}) {
  const toast = useToast();
  const nav = useNavigate();
  const t = useTr();

  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(DEFAULT_LIMIT);
  const [keyword, setKeyword] = useState(initialQuery ?? '');
  const [filter, setFilter] = useState<string | number | null>(null);
  const [tick, setTick] = useState(0);

  const [rows, setRows] = useState<Row[]>([]);
  const [total, setTotal] = useState(0);
  const [paginated, setPaginated] = useState(cfg.paginated !== false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [editing, setEditing] = useState<Row | 'new' | null>(null);
  const [detail, setDetail] = useState<Row | null>(null);
  const [pending, setPending] = useState<{
    kind: 'delete' | 'action';
    row: Row;
    act?: ActionDef;
  } | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    let alive = true;
    (async () => {
      setLoading(true);
      setError(null);
      const params: Record<string, string | number | undefined | null> = {
        ...(cfg.params ?? {}),
        keyword: keyword || undefined,
      };
      if (cfg.filters && filter !== null) params[cfg.filters.key] = filter;
      if (paginated) {
        params.page = page;
        params.limit = Math.min(limit, MAX_LIMIT);
      }
      try {
        const data = await api<Row[] | PageData<Row>>(
          `${cfg.endpoint}${qs(params)}`,
        );
        if (!alive) return;
        if (Array.isArray(data)) {
          setRows(data);
          setTotal(data.length);
          setPaginated(false);
        } else {
          setRows(data.list ?? []);
          setTotal(data.total ?? 0);
          setPaginated(true);
        }
      } catch (e) {
        if (!alive) return;
        setError(e instanceof Error ? e.message : '加载失败');
      } finally {
        if (alive) setLoading(false);
      }
    })();
    return () => {
      alive = false;
    };
  }, [cfg.endpoint, cfg.params, cfg.filters, cfg.paginated, page, limit, keyword, filter, tick]);

  const refresh = () => setTick((t) => t + 1);

  // 关联列的名称来自其它资源：先把 fields 声明的 source 预取进共享缓存，
  // 到货后 bump 一次触发重渲染，让 id 占位换成名称
  const [, bumpOpts] = useState(0);
  useEffect(() => {
    const endpoints = [
      ...new Set((cfg.fields ?? []).flatMap((f) => (f.source ? [f.source.endpoint] : []))),
    ];
    if (endpoints.length === 0) return;
    let alive = true;
    Promise.all(endpoints.map(prefetch)).then(() => {
      if (alive) bumpOpts((n) => n + 1);
    });
    return () => {
      alive = false;
    };
  }, [cfg.fields]);

  const doDelete = async (row: Row, password: string) => {
    const id = String(take(row, 'id') ?? '');
    setBusy(true);
    try {
      // 敏感资源（用户/角色/权限）删除需二次密码，后端 confirmPassword 校验
      await api(`${cfg.endpoint}/${id}`, {
        method: 'DELETE',
        body: cfg.deleteNeedsPassword ? { password } : undefined,
      });
      toast(t('删除成功'), 'ok');
      setPending(null);
      refresh();
    } catch (e) {
      toast(msg(e));
    } finally {
      setBusy(false);
    }
  };

  const runAction = async (act: ActionDef, row: Row, password: string) => {
    const path = act.path?.(row);
    if (!path) return;
    setBusy(true);
    try {
      const body = act.body?.(row, password) ?? {};
      if (act.method === 'GET') await api(path);
      else if (act.method === 'PUT') await api(path, { method: 'PUT', body });
      else await api(path, { method: 'POST', body });
      toast(act.message ? t(act.message) : t('操作成功'), 'ok');
      setPending(null);
      refresh();
      if (act.navTo) nav(act.navTo(row));
    } catch (e) {
      toast(msg(e));
    } finally {
      setBusy(false);
    }
  };

  const actions = (row: Row) => (
    <div className="row-actions">
      <Btn variant="icon" icon="eye" title={t('详情')} onClick={() => setDetail(row)} />
      {cfg.fields && (
        <Btn variant="icon" icon="edit" title={t('编辑')} onClick={() => setEditing(row)} />
      )}
      {cfg.actions?.map((a) => {
        if (a.path && a.path(row) === null) return null;
        const iconOnly = !a.variant || a.variant.startsWith('icon');
        return (
          <Btn
            key={a.label}
            variant={a.variant ?? 'sm'}
            icon={a.icon}
            title={t(a.label)}
            onClick={() => setPending({ kind: 'action', row, act: a })}
          >
            {iconOnly ? null : t(a.label)}
          </Btn>
        );
      })}
      {cfg.canDelete !== false && (
        <Btn
          variant="icon-danger"
          icon="trash"
          title={t('删除')}
          onClick={() => setPending({ kind: 'delete', row })}
        />
      )}
    </div>
  );

  const cols = [
    ...(cfg.columns ?? inferColumns(rows, cfg.endpoint, cfg.fields)),
    {
      key: '__actions',
      title: '操作',
      width: Math.max(86, 32 * actionCount(cfg)),
      render: actions,
    },
  ];

  return (
    <>
      <PageHead title={cfg.title} total={paginated ? total : undefined} accent={accentOf(cfg.moduleKey)}>
        <Btn variant="outline" icon="refresh" onClick={refresh} title={t('刷新')}>
          {t('刷新')}
        </Btn>
        {cfg.fields && (
          <Btn variant="primary" icon="plus" onClick={() => setEditing('new')}>
            {t('新增')}
          </Btn>
        )}
      </PageHead>

      <div className="card body">
        <div className="toolbar">
          <Input
            className="search-input"
            placeholder={cfg.searchPlaceholder ? t(cfg.searchPlaceholder) : t('输入关键词搜索')}
            value={keyword}
            onChange={(e) => {
              setKeyword(e.target.value);
              setPage(1);
            }}
          />
          <span className="grow" />
          {cfg.extraToolbar?.({ refresh })}
          <Select
            value={String(limit)}
            onChange={(e) => {
              setLimit(Number(e.target.value));
              setPage(1);
            }}
            style={{ width: 108 }}
            disabled={!paginated}
          >
            {[15, 30, 50, 100].map((n) => (
              <option key={n} value={n}>
                {n} {t('条/页')}
              </option>
            ))}
          </Select>
        </div>

        {cfg.filters && (
          <Chips
            options={cfg.filters.options}
            value={filter}
            onChange={(v) => {
              setFilter(v);
              setPage(1);
            }}
          />
        )}

        <DataTable
          columns={cols}
          rows={rows}
          loading={loading}
          error={error}
          onRetry={refresh}
          total={total}
          page={page}
          limit={limit}
          onPage={setPage}
          showPager={paginated}
          emptyDesc={cfg.emptyDesc}
        />
      </div>

      {editing && (
        <FormDialog
          cfg={cfg}
          row={editing === 'new' ? null : editing}
          onClose={() => setEditing(null)}
          onSaved={() => {
            setEditing(null);
            refresh();
          }}
        />
      )}

      {detail && (
        <Modal title={cfg.title} onClose={() => setDetail(null)} wide>
          {cfg.detail ? (
            cfg.detail(detail)
          ) : (
            <DescList items={inferDetailItems(detail)} />
          )}
        </Modal>
      )}

      {pending && (
        <ConfirmDialog
          title={pending.kind === 'delete' ? t('确认删除') : (pending.act?.label ? t(pending.act.label) : t('确认操作'))}
          message={
            pending.kind === 'delete'
              ? t('确定删除「{name}」？该操作不可恢复。', { name: text(rowLabel(pending.row)) })
              : t('确定执行「{act}」吗？', { act: pending.act?.label ?? '' })
          }
          requirePassword={
            pending.kind === 'delete'
              ? cfg.deleteNeedsPassword === true
              : pending.act?.requirePassword === true
          }
          loading={busy}
          onOk={(pw) =>
            pending.kind === 'delete'
              ? doDelete(pending.row, pw)
              : pending.act
                ? runAction(pending.act, pending.row, pw)
                : undefined
          }
          onClose={() => {
            if (!busy) setPending(null);
          }}
        />
      )}
    </>
  );
}

/** 操作列按钮数（详情+编辑+业务动作+删除），用于预留列宽 */
function actionCount(cfg: import('@/config/types').ResourceConfig): number {
  let n = 2;
  if (cfg.fields) n += 1;
  return n + (cfg.actions?.length ?? 0);
}

/** 行的可读标识，用于确认弹窗文案 */
function rowLabel(row: Row): string {
  return String(row.code ?? row.name ?? row.title ?? row.username ?? row.id ?? '');
}

/** 声明式表单弹窗 */
function FormDialog({
  cfg,
  row,
  onClose,
  onSaved,
}: {
  cfg: import('@/config/types').ResourceConfig;
  row: Row | null;
  onClose: () => void;
  onSaved: () => void;
}) {
  const toast = useToast();
  const t = useTr();
  const isNew = row === null;
  const [vals, setVals] = useState<Record<string, unknown>>(() => {
    const init: Record<string, unknown> = {};
    for (const f of cfg.fields ?? []) {
      if (isNew && f.editOnly) continue;
      if (!isNew && f.createOnly) continue;
      init[f.key] = f.defaultValue ?? row?.[f.key] ?? '';
    }
    return init;
  });
  const [busy, setBusy] = useState(false);
  /** 数据联动下拉的远程选项，key = 字段名；打开表单时按 source 拉取 */
  const [remote, setRemote] = useState<Record<string, FieldOption[]>>({});

  useEffect(() => {
    let alive = true;
    const sources = (cfg.fields ?? []).filter((f): f is FormField & { source: FieldSource } => Boolean(f.source));
    if (sources.length === 0) return;
    (async () => {
      const next: Record<string, FieldOption[]> = {};
      await Promise.all(
        sources.map(async (f) => {
          next[f.key] = await loadOptions(f.source);
        }),
      );
      if (alive) setRemote(next);
    })();
    return () => {
      alive = false;
    };
  }, [cfg.fields]);

  const set = (k: string, v: unknown) => setVals((s) => ({ ...s, [k]: v }));

  const submit = async () => {
    for (const f of cfg.fields ?? []) {
      if (f.noSubmit) continue;
      if (isNew && f.editOnly) continue;
      if (!isNew && f.createOnly) continue;
      if (f.required && (vals[f.key] === '' || vals[f.key] === null || vals[f.key] === undefined)) {
        toast(t('请填写「{label}」', { label: f.label }));
        return;
      }
    }
    const body: Record<string, unknown> = {};
    for (const f of cfg.fields ?? []) {
      if (f.noSubmit) continue;
      if (isNew && f.editOnly) continue;
      if (!isNew && f.createOnly) continue;
      let v = vals[f.key];
      if (v === '') v = undefined;
      if (v !== undefined) body[f.key] = v;
    }
    setBusy(true);
    try {
      if (isNew) await http.post(cfg.endpoint, body);
      else await http.put(`${cfg.endpoint}/${String(row?.id)}`, body);
      toast(isNew ? t('新增成功') : t('保存成功'), 'ok');
      onSaved();
    } catch (e) {
      toast(msg(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <Modal
      title={
        isNew
          ? (cfg.createTitle ? t(cfg.createTitle) : t('新增{name}', { name: cfg.title.replace(/管理|列表/g, '') }))
          : (cfg.editTitle ? t(cfg.editTitle) : t('编辑{name}', { name: cfg.title.replace(/管理|列表/g, '') }))
      }
      onClose={onClose}
      wide={(cfg.fields ?? []).some((f) => f.full || f.type === 'textarea')}
      footer={
        <>
          <Btn onClick={onClose}>{t('取消')}</Btn>
          <Btn variant="primary" loading={busy} onClick={submit}>
            {t('保存')}
          </Btn>
        </>
      }
    >
      <div className="fields">
        {(cfg.fields ?? [])
          .filter((f) => (isNew ? !f.editOnly : !f.createOnly))
          .map((f) => {
            const val = vals[f.key] ?? '';
            const common = {
              value: val as string,
              disabled: f.disabled,
              placeholder: f.placeholder ? t(f.placeholder) : undefined,
              onChange: (e: { target: { value: string } }) =>
                set(f.key, f.type === 'number' ? (e.target.value === '' ? '' : Number(e.target.value)) : e.target.value),
            };
            return (
              <Field key={f.key} label={f.label} required={f.required} full={f.full} help={f.help}>
                {f.type === 'textarea' ? (
                  <Textarea {...common} />
                ) : f.type === 'select' || f.source ? (
                  <Select {...common}>
                    <option value="">{t('请选择')}</option>
                    {(f.options ?? remote[f.key] ?? []).map((o) => (
                      <option key={String(o.value)} value={String(o.value)}>
                        {t(o.label)}
                      </option>
                    ))}
                  </Select>
                ) : f.type === 'password' ? (
                  <Input type="password" {...common} />
                ) : f.type === 'date' ? (
                  <Input type="date" {...common} />
                ) : f.type === 'datetime' ? (
                  <Input type="datetime-local" {...common} />
                ) : (
                  <Input type={f.type === 'number' ? 'number' : 'text'} {...common} />
                )}
              </Field>
            );
          })}
      </div>
    </Modal>
  );
}

function msg(e: unknown): string {
  return e instanceof Error ? e.message : '操作失败';
}
